version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jewelry_store_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build:
      context: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:



